package me.playbosswar.playapi.arena;

import me.playbosswar.playapi.arena.events.ArenaJoinEvent;
import me.playbosswar.playapi.spawnpoints.SpawnPointDefiner;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;

import java.io.File;
import java.util.Set;
import java.util.UUID;

public class Arena {
    private final UUID uuid;
    private String name;
    private Boolean enabled;
    private ArenaState state = ArenaState.WAITING;
    private final int minPlayers;
    private final int maxPlayers;
    // This file is internal, generated by PlayAPI itself
    private File schematicFile;
    private Set<Player> players;
    private SpawnPointDefiner spawnPointDefiner;
    private Location lowerBound;
    private Location upperBound;
    private final WaitingLobbyManager waitingLobbyManager;

    public Arena(String name, UUID uuid, WaitingLobbyManager waitingLobbyManager, int minPlayers, int maxPlayers) {
        this.name = name;
        this.uuid = uuid;
        this.waitingLobbyManager = waitingLobbyManager;
        this.minPlayers = minPlayers;
        this.maxPlayers = maxPlayers;
    }

    public UUID getUuid() {
        return uuid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public SpawnPointDefiner getSpawnPointDefiner() {
        return spawnPointDefiner;
    }

    public Arena setSpawnPointDefiner(SpawnPointDefiner spawnPointDefiner) {
        this.spawnPointDefiner = spawnPointDefiner;
        return this;
    }

    public File getSchematicFile() {
        return schematicFile;
    }

    public void setSchematicFile(File schematicFile) {
        this.schematicFile = schematicFile;
    }

    public void addPlayer(Player player) {
        ArenaJoinEvent event = new ArenaJoinEvent(this, player);
        Bukkit.getPluginManager().callEvent(event);
        if (!event.isCancelled()) {
            this.players.add(player);
            player.teleport(this.waitingLobbyManager.getSpawnLocation(player));
            player.getInventory().setContents(this.waitingLobbyManager.getItems(player).toArray(new ItemStack[]{}));
        }
    }
}
